Validations and model specs
AnsarIbrahim/Bloggy pull request #3
Opened 2023-09-20 17:29 UTC by AnsarIbrahim

# This PR Contains:

# Project requirements
- Add validations to User and Post what they require✅
- Write unit test for all models✅

2023-09-20 18:02 UTC, Lucas-Masaba requested changes
# Hello @AnsarIbrahim  👋 , 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

## Highlights 🍾 
- Linter checks passing :heavy_check_mark: 
- All written tests are passing :heavy_check_mark: 
- Successfully added validations to your models :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 💭 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-20 18:02 UTC, Lucas-Masaba commented on app/models/post.rb
> +  validates :title, presence: true, length: { minimum: 5 }
- [ ] According to the project requirements, the length should be a maximum of 250 characters
![image](https://github.com/AnsarIbrahim/Bloggy/assets/45460192/34c06b33-1c26-482d-821b-875a63f76ec5)

2023-09-20 18:02 UTC, Lucas-Masaba commented on spec/models/user_spec.rb
> +    end
- [ ] As mentioned in the project requirements, any custom methods in the models should have a corresponding test. Please test the `recent_posts` model in your User model.

2023-09-20 18:02 UTC, Lucas-Masaba commented on spec/models/post_spec.rb
> +    expect(user.reload.post_counter).to eq(1)
- [ ] Please add tests for the `recent_comments` and `update_posts_counter` methods found in your Post model.

2023-09-20 18:02 UTC, Lucas-Masaba commented on spec/models/like_spec.rb
> +    end
- [ ] Please add tests for your `update_likes` method in your Like model

2023-09-20 18:02 UTC, Lucas-Masaba commented on spec/models/comment_spec.rb
> +    end
- [ ] Please add a test for your `update_comments_counter` method in your Comment model.

2023-09-21 00:00 UTC, Owusu-Desmond approved these changes
Hi @AnsarIbrahim , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-21 07:35 UTC, merged